version : 2

sources:
  - name: raw  # This is the first argument to source()
    database: dbt_sqlmesh # Or use a variable
    schema: raw
    tables:
      - name: customers # This is the second argument to source()
      - name: orders